version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/fit-folio-2
      - JWT_SECRET=kmhdfg98723tHGKJRYC&^%(Nu76yrfbksg9)_9ih
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    ports:
      - '6379:6379'
volumes:
  mongo-data:
